version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - ./run/var:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    image: federicoledesma/sip2020-sommer:1.0
    depends_on:
      - mysql
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: laravel_mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_password

volumes:
  mysql_data:
